### ISSUE TITLE
Practica 3 Visual Studio Interfaz Grafica Menu

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-equipohjf#1]
El estudiante debe diseñar en Visual Studio un prototipo nativo en c# para implementar eventos con el ratón presentando un reporte de practica 3.

1. Diseñar una interfaz gráfica para el desarrollo de la Aplicación como proyecto.

2. Diseñar las opciones del menú principal de la Aplicación.

3. Utilizar las caracteristicas de Usabilidad y diseño para la Aplicación

4. El menú de la Aplicación debe ser diseñada en Visual Studio

**Comment by FedericoVictorianoSierra** [comment]
[Practica 3 ( Federico Victoriano Sierra(4US)).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-equipohjf/files/8121685/Practica.3.Federico.Victoriano.Sierra.4US.pdf)

**Comment by JoseABCruz** [comment]
[Practica 3 (José Antonio Balbuena Cruz (4US)).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-equipohjf/files/8121777/Practica.3.Jose.Antonio.Balbuena.Cruz.4US.pdf)

**Comment by Heidi-19** [comment]
[Practica 3 (Heidi Lucy Bautista Sanjuan 4US).pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-equipohjf/files/8121828/Practica.3.Heidi.Lucy.Bautista.Sanjuan.4US.pdf)

**Comment by IrvingFernand0** [comment]
Calificación practica 3 : 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
